// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSitesi_API_1.Models;

#nullable disable

namespace YemekSitesi_API_1.Migrations
{
    [DbContext(typeof(YemekSitesiDbContext))]
    [Migration("20231013073800_sepetDataSeeding")]
    partial class sepetDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekSitesi_API_1.Models.Adres_1", b =>
                {
                    b.Property<int>("adresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adresID"));

                    b.Property<string>("evAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("isAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("adresID");

                    b.ToTable("Adressler");

                    b.HasData(
                        new
                        {
                            adresID = 100,
                            evAdresi = "No: 12, Cumhuriyet Caddesi, İstiklal Mahallesi, İstanbul, 34000",
                            isAdresi = " No: 10, İş Merkezi Caddesi, Merkez Mahallesi, Ankara, 06500"
                        },
                        new
                        {
                            adresID = 101,
                            evAdresi = "No: 5, Atatürk Bulvarı, Kızılay Mahallesi, Ankara, 06000",
                            isAdresi = "No: 15, İş Parkı Sokak, Finans Mahallesi, İstanbul, 34000"
                        },
                        new
                        {
                            adresID = 102,
                            evAdresi = "No: 21/A, Mimar Sinan Sokak, Konak Mahallesi, İzmir, 35000",
                            isAdresi = "No: 7, Plaza Yolu, Ticaret Mahallesi, İzmir, 35000"
                        },
                        new
                        {
                            adresID = 103,
                            evAdresi = "No: 8, İstiklal Mahallesi, Osmangazi Sokak, Bursa, 16000",
                            isAdresi = "No: 25/A, İşhanı Caddesi, Sanayi Mahallesi, Bursa, 16000"
                        },
                        new
                        {
                            adresID = 104,
                            evAdresi = "No: 3, Fatih Sultan Mehmet Caddesi, Lara Mahallesi, Antalya, 07000",
                            isAdresi = "No: 4, Ofis Sokak, Rezidans Mahallesi, Antalya, 07000"
                        },
                        new
                        {
                            adresID = 105,
                            evAdresi = "No: 7, Mevlana  Caddesi, Emirler Mahallesi, Eskişehir, 03000",
                            isAdresi = "No: 4, Paşa Sokak, Duran Mahallesi, Ankara, 01000"
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Kategoriler_1", b =>
                {
                    b.Property<int>("kategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kategoriID"));

                    b.Property<string>("kategoriImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kategoriTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("kategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            kategoriID = 500,
                            kategoriImg = "https://cdn.pixabay.com/photo/2021/05/07/08/46/ground-beef-6235546_1280.jpg",
                            kategoriTuru = "Pide/Lahmacun"
                        },
                        new
                        {
                            kategoriID = 501,
                            kategoriImg = "https://cdn.pixabay.com/photo/2022/07/21/14/13/baklava-7336361_1280.jpg",
                            kategoriTuru = "Pasta/Tatlı"
                        },
                        new
                        {
                            kategoriID = 502,
                            kategoriImg = "https://cdn.pixabay.com/photo/2015/05/25/16/14/burger-783551_1280.jpg",
                            kategoriTuru = "Mangal / Barbekü"
                        },
                        new
                        {
                            kategoriID = 503,
                            kategoriImg = "https://cdn.pixabay.com/photo/2014/11/05/15/57/salmon-518032_1280.jpg",
                            kategoriTuru = "Balık/Deniz Ürünleri"
                        },
                        new
                        {
                            kategoriID = 504,
                            kategoriImg = "https://cdn.pixabay.com/photo/2017/07/19/15/17/bulgur-2519399_1280.jpg",
                            kategoriTuru = "Türk Mutfağı/Sıcak Yemek"
                        },
                        new
                        {
                            kategoriID = 505,
                            kategoriImg = "https://cdn.pixabay.com/photo/2021/01/01/15/31/sushi-balls-5878892_1280.jpg",
                            kategoriTuru = "Asya Mutfağı"
                        },
                        new
                        {
                            kategoriID = 506,
                            kategoriImg = "https://cdn.pixabay.com/photo/2021/03/24/08/49/durum-6119590_1280.jpg",
                            kategoriTuru = "Kebap/Döner/Dürüm"
                        },
                        new
                        {
                            kategoriID = 507,
                            kategoriImg = "https://cdn.pixabay.com/photo/2017/10/18/16/23/bread-2864665_1280.jpg",
                            kategoriTuru = "Fırın/Börek"
                        },
                        new
                        {
                            kategoriID = 508,
                            kategoriImg = "https://cdn.pixabay.com/photo/2017/05/11/19/49/iced-coffee-2305203_1280.jpg",
                            kategoriTuru = "İçecekler"
                        },
                        new
                        {
                            kategoriID = 509,
                            kategoriImg = "https://cdn.pixabay.com/photo/2018/07/14/21/30/club-sandwich-3538455_1280.jpg",
                            kategoriTuru = "Tost/bistro/Sandviç"
                        },
                        new
                        {
                            kategoriID = 510,
                            kategoriImg = "https://cdn.pixabay.com/photo/2018/10/01/18/20/raw-meat-3716962_1280.jpg",
                            kategoriTuru = "Yan Lezzetler/Çiğköfte"
                        },
                        new
                        {
                            kategoriID = 511,
                            kategoriImg = "https://cdn.pixabay.com/photo/2016/03/05/19/02/hamburger-1238246_1280.jpg",
                            kategoriTuru = "Hamburger"
                        },
                        new
                        {
                            kategoriID = 512,
                            kategoriImg = "https://cdn.pixabay.com/photo/2017/12/10/14/47/pizza-3010062_1280.jpg",
                            kategoriTuru = "Pizza/Makarna"
                        },
                        new
                        {
                            kategoriID = 513,
                            kategoriImg = "https://cdn.pixabay.com/photo/2022/05/17/04/57/broasted-chicken-7201660_1280.jpg",
                            kategoriTuru = "Tavuk"
                        },
                        new
                        {
                            kategoriID = 514,
                            kategoriImg = "https://cdn.pixabay.com/photo/2017/06/17/16/20/waffles-2412628_1280.jpg",
                            kategoriTuru = "Waffle/Dondurma"
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Kullanicilar_1", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("adresId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("userID");

                    b.HasIndex("adresId")
                        .IsUnique();

                    b.ToTable("Kullanıcılar");

                    b.HasData(
                        new
                        {
                            userID = 200,
                            ad = "Ahmet",
                            adresId = 100,
                            email = "ahmet.yilmaz @example.com",
                            isactive = true,
                            password = "Sifre12!",
                            role = "person",
                            soyad = "Yılmaz",
                            tel = "5551234567"
                        },
                        new
                        {
                            userID = 201,
                            ad = "Ayşe",
                            adresId = 101,
                            email = "ayse.kaya @example.com",
                            isactive = true,
                            password = "Gec3Tr!k",
                            role = "person",
                            soyad = "Kaya",
                            tel = "5559876543"
                        },
                        new
                        {
                            userID = 202,
                            ad = "Mehmet",
                            adresId = 102,
                            email = "mehmet.demir @example.com",
                            isactive = true,
                            password = "P@ssw0rd",
                            role = "person",
                            soyad = "Demir",
                            tel = "5552345678"
                        },
                        new
                        {
                            userID = 203,
                            ad = "Elif",
                            adresId = 103,
                            email = "elif.ozturk @example.com",
                            isactive = true,
                            password = "9b1!O9by",
                            role = "person",
                            soyad = "Öztürk",
                            tel = "5558765432"
                        },
                        new
                        {
                            userID = 204,
                            ad = "Can",
                            adresId = 104,
                            email = "can.aksoy @example.com",
                            isactive = true,
                            password = "$tr0ngP@",
                            role = "person",
                            soyad = "Aksoy",
                            tel = "5553456789"
                        },
                        new
                        {
                            userID = 205,
                            ad = "Hatice",
                            adresId = 105,
                            email = "admin01@example.com",
                            isactive = true,
                            password = "Admin*01",
                            role = "admin",
                            soyad = "Düş",
                            tel = "5553456789"
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Menu_1", b =>
                {
                    b.Property<int>("menuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("menuID"));

                    b.Property<string>("menuAdi")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("menuImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("menuID");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            menuID = 700,
                            menuAdi = "Kebap Ekonomik Menü_1",
                            menuImg = "https://cdn.getiryemek.com/restaurants/1619394979049_1125x522.jpeg"
                        },
                        new
                        {
                            menuID = 701,
                            menuAdi = "Mix_1 Tatlı Menüsü",
                            menuImg = "https://cdn.pixabay.com/photo/2020/03/11/20/10/dessert-4923228_640.jpg"
                        },
                        new
                        {
                            menuID = 702,
                            menuAdi = "Deniz_1",
                            menuImg = "https://cdn.pixabay.com/photo/2023/05/17/15/58/shrimp-8000536_640.jpg"
                        },
                        new
                        {
                            menuID = 703,
                            menuAdi = "Mangal Karışık Menü_1",
                            menuImg = "https://cdn.pixabay.com/photo/2017/02/25/15/23/barbecue-2098020_1280.jpg"
                        },
                        new
                        {
                            menuID = 704,
                            menuAdi = "Özel Pide Menüsü_1",
                            menuImg = "https://cdn.pixabay.com/photo/2018/04/21/21/50/food-3339651_640.jpg"
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Menuler_1", b =>
                {
                    b.Property<int>("menulerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("menulerID"));

                    b.Property<int>("menuID")
                        .HasColumnType("int");

                    b.Property<int>("urunID")
                        .HasColumnType("int");

                    b.HasKey("menulerID");

                    b.HasIndex("menuID");

                    b.HasIndex("urunID");

                    b.ToTable("Menuler");

                    b.HasData(
                        new
                        {
                            menulerID = 800,
                            menuID = 700,
                            urunID = 900
                        },
                        new
                        {
                            menulerID = 801,
                            menuID = 700,
                            urunID = 903
                        },
                        new
                        {
                            menulerID = 802,
                            menuID = 700,
                            urunID = 904
                        },
                        new
                        {
                            menulerID = 803,
                            menuID = 701,
                            urunID = 901
                        },
                        new
                        {
                            menulerID = 804,
                            menuID = 701,
                            urunID = 906
                        },
                        new
                        {
                            menulerID = 805,
                            menuID = 701,
                            urunID = 908
                        },
                        new
                        {
                            menulerID = 806,
                            menuID = 702,
                            urunID = 909
                        },
                        new
                        {
                            menulerID = 807,
                            menuID = 702,
                            urunID = 911
                        },
                        new
                        {
                            menulerID = 808,
                            menuID = 702,
                            urunID = 912
                        },
                        new
                        {
                            menulerID = 809,
                            menuID = 703,
                            urunID = 914
                        },
                        new
                        {
                            menulerID = 810,
                            menuID = 703,
                            urunID = 916
                        },
                        new
                        {
                            menulerID = 811,
                            menuID = 703,
                            urunID = 905
                        },
                        new
                        {
                            menulerID = 812,
                            menuID = 704,
                            urunID = 903
                        },
                        new
                        {
                            menulerID = 813,
                            menuID = 704,
                            urunID = 919
                        },
                        new
                        {
                            menulerID = 814,
                            menuID = 704,
                            urunID = 917
                        },
                        new
                        {
                            menulerID = 815,
                            menuID = 704,
                            urunID = 918
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_1", b =>
                {
                    b.Property<int>("restaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restaurantID"));

                    b.Property<int?>("Kategoriler_1kategoriID")
                        .HasColumnType("int");

                    b.Property<string>("restaurantAd")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("restaurantAdres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("restaurantImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("restaurantTel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("restaurantID");

                    b.HasIndex("Kategoriler_1kategoriID");

                    b.ToTable("Restaurantlar");

                    b.HasData(
                        new
                        {
                            restaurantID = 400,
                            restaurantAd = "Lezzet Durağı",
                            restaurantAdres = "İstiklal Caddesi No: 123, İstanbul",
                            restaurantImg = "https://vegfusionblog.files.wordpress.com/2023/05/soya-etli-sote.png",
                            restaurantTel = "5551234567"
                        },
                        new
                        {
                            restaurantID = 401,
                            restaurantAd = "Tatlının Şahı",
                            restaurantAdres = "Merkez Mahallesi, Atatürk Bulvarı No: 45, Ankara",
                            restaurantImg = "https://cdn.pixabay.com/photo/2016/08/12/16/01/cake-1589012_1280.jpg",
                            restaurantTel = "5559876543"
                        },
                        new
                        {
                            restaurantID = 402,
                            restaurantAd = "Deniz Köşesi",
                            restaurantAdres = "Sahil Yolu Sokak No: 67, İzmir",
                            restaurantImg = "https://cdn.getiryemek.com/restaurants/1601032811170_1125x522.jpeg",
                            restaurantTel = "5552345678"
                        },
                        new
                        {
                            restaurantID = 403,
                            restaurantAd = "Mangal Keyfi",
                            restaurantAdres = "Göztepe Mahallesi, İstiklal Caddesi No: 89, Bursa",
                            restaurantImg = "https://media.istockphoto.com/id/953028822/tr/foto%C4%9Fraf/izgara-sosis-ve-a%C3%A7%C4%B1k-bir-%C4%B1zgara-tabakta-sebze.webp?b=1&s=612x612&w=0&k=20&c=YgQexq06_E4AqasLUJNjRmrvB8tcnzso0_DKrSLDigY=",
                            restaurantTel = "5558765432"
                        },
                        new
                        {
                            restaurantID = 404,
                            restaurantAd = "Pidecim",
                            restaurantAdres = "Meşrutiyet Mahallesi, Cumhuriyet Sokak No: 21, Antalya",
                            restaurantImg = "https://cdn.pixabay.com/photo/2018/04/21/21/50/food-3339651_640.jpg",
                            restaurantTel = "5553456789"
                        },
                        new
                        {
                            restaurantID = 405,
                            restaurantAd = "Ayten usta",
                            restaurantAdres = "Yeşilova, 4016. Cad. No:10 BJ, 06796 Etimesgut/Ankara",
                            restaurantImg = "https://www.isvecgundemi.com/images/upload/61565937_2387274074628029_7825222120283045888_o_3.jpg",
                            restaurantTel = "5365434936"
                        },
                        new
                        {
                            restaurantID = 406,
                            restaurantAd = "Domino's Pizza",
                            restaurantAdres = "1464. Cad. 1472 Sok. No:1/10 Elvankent, Ankara",
                            restaurantImg = "https://cdn.getiryemek.com/restaurants/1617109990692_1125x522.jpeg",
                            restaurantTel = "2126359874"
                        },
                        new
                        {
                            restaurantID = 407,
                            restaurantAd = "Papa John's Pizza",
                            restaurantAdres = "1904 Cadde Tekgül Sitesi No :16, Ankara",
                            restaurantImg = "https://yiyegeze.com/wp-content/uploads/2020/01/images-3-2.jpg",
                            restaurantTel = "2224569872"
                        },
                        new
                        {
                            restaurantID = 408,
                            restaurantAd = "Little Caesars Pizza",
                            restaurantAdres = "Ahmet Taner Kışlalı Mah. Park Cad. 2866 Sok. No:38/5 Çayyolu, Ankara",
                            restaurantImg = "https://www.littlecaesars.com.tr/CMSFiles/Product/LittleImage/tek-pizzalar.jpg",
                            restaurantTel = "2145664412"
                        },
                        new
                        {
                            restaurantID = 409,
                            restaurantAd = "Pizza Hut",
                            restaurantAdres = "Yıldızevler Mah. 4. Cad. No:43/A Yıldız, Ankara",
                            restaurantImg = "https://media-cdn.tripadvisor.com/media/photo-s/20/9f/25/59/great-food.jpg",
                            restaurantTel = "5463217896"
                        },
                        new
                        {
                            restaurantID = 410,
                            restaurantAd = "Sbarro Pizza",
                            restaurantAdres = "ERYAMAN MAH. DUMLUPINAR 30 AĞUSTOS CAD. NO:2-A, X Ankara",
                            restaurantImg = "https://images.deliveryhero.io/image/fd-tr/LH/qql7-hero.jpg?width=1600",
                            restaurantTel = "2125641236"
                        },
                        new
                        {
                            restaurantID = 411,
                            restaurantAd = "Pizza Lovers",
                            restaurantAdres = "BALGAT MAH. ZİYABEY CAD. NO: 59 E ÇANKAYA/ ANKARA,",
                            restaurantImg = "https://images.deliveryhero.io/image/fd-tr/LH/k5fn-hero.jpg?width=1000",
                            restaurantTel = "5369636514"
                        },
                        new
                        {
                            restaurantID = 412,
                            restaurantAd = "Tadım Pizza",
                            restaurantAdres = "Dikmen Cad. No: 440/B Dikmen, Ankara",
                            restaurantImg = "https://images.deliveryhero.io/image/fd-tr/LH/ghuo-hero.jpg?width=1000",
                            restaurantTel = "5417896352"
                        },
                        new
                        {
                            restaurantID = 413,
                            restaurantAd = "Pizza Bulls",
                            restaurantAdres = "Turgut Özal Mah. 2154 Cad. No:11/B Blok 4 Yenimahalle – ANKARA",
                            restaurantImg = "https://images.deliveryhero.io/image/fd-tr/LH/jxms-hero.jpg?width=1000",
                            restaurantTel = "5423217744"
                        },
                        new
                        {
                            restaurantID = 414,
                            restaurantAd = "Başak Kır Pidesi",
                            restaurantAdres = "Kentkoop Mah. Batıkent/Yenimahalle, ANKARA",
                            restaurantImg = "https://cdn.getiryemek.com/restaurants/1686741420103_1125x522.jpeg",
                            restaurantTel = "2551478963"
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_Menu_1", b =>
                {
                    b.Property<int>("restMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restMenuID"));

                    b.Property<int>("menuID")
                        .HasColumnType("int");

                    b.Property<int>("restaurantID")
                        .HasColumnType("int");

                    b.HasKey("restMenuID");

                    b.HasIndex("menuID");

                    b.HasIndex("restaurantID");

                    b.ToTable("Restaurant_Menu");

                    b.HasData(
                        new
                        {
                            restMenuID = 600,
                            menuID = 704,
                            restaurantID = 404
                        },
                        new
                        {
                            restMenuID = 601,
                            menuID = 700,
                            restaurantID = 400
                        },
                        new
                        {
                            restMenuID = 602,
                            menuID = 703,
                            restaurantID = 403
                        },
                        new
                        {
                            restMenuID = 603,
                            menuID = 701,
                            restaurantID = 401
                        },
                        new
                        {
                            restMenuID = 604,
                            menuID = 702,
                            restaurantID = 402
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_Urun_1", b =>
                {
                    b.Property<int>("restUrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restUrunID"));

                    b.Property<int>("restaurantID")
                        .HasColumnType("int");

                    b.Property<int>("urunID")
                        .HasColumnType("int");

                    b.HasKey("restUrunID");

                    b.HasIndex("restaurantID");

                    b.HasIndex("urunID");

                    b.ToTable("Restaurant_Urun");

                    b.HasData(
                        new
                        {
                            restUrunID = 1000,
                            restaurantID = 404,
                            urunID = 903
                        },
                        new
                        {
                            restUrunID = 1001,
                            restaurantID = 400,
                            urunID = 900
                        },
                        new
                        {
                            restUrunID = 1002,
                            restaurantID = 400,
                            urunID = 903
                        },
                        new
                        {
                            restUrunID = 1003,
                            restaurantID = 400,
                            urunID = 904
                        },
                        new
                        {
                            restUrunID = 1004,
                            restaurantID = 403,
                            urunID = 914
                        },
                        new
                        {
                            restUrunID = 1005,
                            restaurantID = 403,
                            urunID = 916
                        },
                        new
                        {
                            restUrunID = 1006,
                            restaurantID = 403,
                            urunID = 905
                        },
                        new
                        {
                            restUrunID = 1007,
                            restaurantID = 401,
                            urunID = 901
                        },
                        new
                        {
                            restUrunID = 1008,
                            restaurantID = 401,
                            urunID = 906
                        },
                        new
                        {
                            restUrunID = 1009,
                            restaurantID = 401,
                            urunID = 908
                        },
                        new
                        {
                            restUrunID = 1010,
                            restaurantID = 402,
                            urunID = 909
                        },
                        new
                        {
                            restUrunID = 1011,
                            restaurantID = 402,
                            urunID = 911
                        },
                        new
                        {
                            restUrunID = 1012,
                            restaurantID = 402,
                            urunID = 912
                        },
                        new
                        {
                            restUrunID = 1013,
                            restaurantID = 404,
                            urunID = 917
                        },
                        new
                        {
                            restUrunID = 1014,
                            restaurantID = 404,
                            urunID = 918
                        },
                        new
                        {
                            restUrunID = 1015,
                            restaurantID = 404,
                            urunID = 919
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Sepet_1", b =>
                {
                    b.Property<int>("sepetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sepetID"));

                    b.Property<string>("productAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("productAdet")
                        .HasColumnType("int");

                    b.Property<DateTime>("productDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("productFiyat")
                        .HasColumnType("int");

                    b.Property<string>("productImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("sepetID");

                    b.HasIndex("userID");

                    b.ToTable("Sepet_1");

                    b.HasData(
                        new
                        {
                            sepetID = 1,
                            productAd = "Baklava",
                            productAdet = 1,
                            productDate = new DateTime(2023, 10, 13, 10, 36, 55, 0, DateTimeKind.Unspecified),
                            productFiyat = 15,
                            productImg = "https://cdn.getiryemek.com/restaurants/1648114161397_1125x522.jpeg",
                            userID = 200
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Siparisler_1", b =>
                {
                    b.Property<int>("siparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("siparisID"));

                    b.Property<int>("menulerID")
                        .HasColumnType("int");

                    b.Property<int>("restaurantID")
                        .HasColumnType("int");

                    b.Property<int>("siparisAdet")
                        .HasColumnType("int");

                    b.Property<DateTime>("siparisTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("siparisTutar")
                        .HasColumnType("int");

                    b.Property<int>("urunID")
                        .HasColumnType("int");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("siparisID");

                    b.HasIndex("menulerID");

                    b.HasIndex("restaurantID");

                    b.HasIndex("urunID");

                    b.HasIndex("userID");

                    b.ToTable("Siparisler");

                    b.HasData(
                        new
                        {
                            siparisID = 300,
                            menulerID = 800,
                            restaurantID = 400,
                            siparisAdet = 2,
                            siparisTarih = new DateTime(2023, 6, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            siparisTutar = 111,
                            urunID = 900,
                            userID = 204
                        },
                        new
                        {
                            siparisID = 301,
                            menulerID = 815,
                            restaurantID = 401,
                            siparisAdet = 3,
                            siparisTarih = new DateTime(2022, 12, 15, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            siparisTutar = 178,
                            urunID = 917,
                            userID = 202
                        },
                        new
                        {
                            siparisID = 302,
                            menulerID = 807,
                            restaurantID = 402,
                            siparisAdet = 1,
                            siparisTarih = new DateTime(2024, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            siparisTutar = 200,
                            urunID = 911,
                            userID = 200
                        },
                        new
                        {
                            siparisID = 303,
                            menulerID = 801,
                            restaurantID = 403,
                            siparisAdet = 5,
                            siparisTarih = new DateTime(2023, 9, 22, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            siparisTutar = 632,
                            urunID = 903,
                            userID = 203
                        },
                        new
                        {
                            siparisID = 304,
                            menulerID = 812,
                            restaurantID = 404,
                            siparisAdet = 2,
                            siparisTarih = new DateTime(2025, 7, 10, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            siparisTutar = 99,
                            urunID = 903,
                            userID = 201
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Urunler_1", b =>
                {
                    b.Property<int>("urunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("urunID"));

                    b.Property<int>("kategoriID")
                        .HasColumnType("int");

                    b.Property<string>("urunAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("urunFiyat")
                        .HasColumnType("int");

                    b.Property<string>("urunImg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("urunID");

                    b.HasIndex("kategoriID");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            urunID = 900,
                            kategoriID = 506,
                            urunAdi = "Adana Kebap",
                            urunFiyat = 100,
                            urunImg = "https://cdn.getiryemek.com/products/1625243947169_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 901,
                            kategoriID = 510,
                            urunAdi = "Patates Kızartması",
                            urunFiyat = 26,
                            urunImg = "https://cdn.getiryemek.com/products/1679877053375_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 902,
                            kategoriID = 510,
                            urunAdi = "Cacık",
                            urunFiyat = 25,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 903,
                            kategoriID = 508,
                            urunAdi = "Ayran",
                            urunFiyat = 10,
                            urunImg = "https://cdn.getiryemek.com/products/1686202547513_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 904,
                            kategoriID = 510,
                            urunAdi = "Semizotu Salatası",
                            urunFiyat = 25,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 905,
                            kategoriID = 501,
                            urunAdi = "Baklava",
                            urunFiyat = 15,
                            urunImg = "https://cdn.getiryemek.com/restaurants/1648114161397_1125x522.jpeg"
                        },
                        new
                        {
                            urunID = 906,
                            kategoriID = 501,
                            urunAdi = "Künefe(2 kişilik)",
                            urunFiyat = 230,
                            urunImg = "https://cdn.getiryemek.com/restaurants/1643656790557_1125x522.jpeg"
                        },
                        new
                        {
                            urunID = 907,
                            kategoriID = 501,
                            urunAdi = "Fıstıklı Kadayıf(1kg)",
                            urunFiyat = 240,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 908,
                            kategoriID = 508,
                            urunAdi = "Salep",
                            urunFiyat = 16,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 909,
                            kategoriID = 503,
                            urunAdi = "Levrek Izgara",
                            urunFiyat = 45,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 910,
                            kategoriID = 503,
                            urunAdi = "Midye Tava",
                            urunFiyat = 32,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 911,
                            kategoriID = 503,
                            urunAdi = "Deniz Mahsulleri Salatası",
                            urunFiyat = 39,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 912,
                            kategoriID = 508,
                            urunAdi = "Limonata",
                            urunFiyat = 14,
                            urunImg = "https://cdn.getiryemek.com/products/1634137936931_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 913,
                            kategoriID = 508,
                            urunAdi = "Kola",
                            urunFiyat = 25,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 914,
                            kategoriID = 506,
                            urunAdi = "Urfa Kebap",
                            urunFiyat = 40,
                            urunImg = "https://cdn.getiryemek.com/products/1625244160417_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 915,
                            kategoriID = 513,
                            urunAdi = "Tavuk Şiş",
                            urunFiyat = 35,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 916,
                            kategoriID = 510,
                            urunAdi = "Pirinç Pilavı",
                            urunFiyat = 14,
                            urunImg = "https://media.istockphoto.com/id/1361129080/tr/foto%C4%9Fraf/traditional-delicious-turkish-food-turkish-style-rice-pilaf.webp?b=1&s=612x612&w=0&k=20&c=3ZDmbKiRRMxZnIR3JFT8oX1wAAhhyS4WsIICDESW6bY="
                        },
                        new
                        {
                            urunID = 917,
                            kategoriID = 508,
                            urunAdi = "Gazoz",
                            urunFiyat = 8,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 918,
                            kategoriID = 510,
                            urunAdi = "Ezme",
                            urunFiyat = 12,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 919,
                            kategoriID = 500,
                            urunAdi = "Kaşarlı Pide",
                            urunFiyat = 28,
                            urunImg = "https://cdn.getiryemek.com/products/1644567963410_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 920,
                            kategoriID = 500,
                            urunAdi = "Sucuklu Pide",
                            urunFiyat = 30,
                            urunImg = "https://cdn.getiryemek.com/products/1634741377114_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 921,
                            kategoriID = 500,
                            urunAdi = "Lahmacun",
                            urunFiyat = 22,
                            urunImg = "https://cdn.getiryemek.com/products/1674032276377_500x375.jpeg"
                        },
                        new
                        {
                            urunID = 922,
                            kategoriID = 510,
                            urunAdi = "Acılı Ezme",
                            urunFiyat = 12,
                            urunImg = ""
                        },
                        new
                        {
                            urunID = 923,
                            kategoriID = 503,
                            urunAdi = "Kalamar",
                            urunFiyat = 55,
                            urunImg = "https://cdn.pixabay.com/photo/2016/03/28/10/01/food-1285314_640.jpg"
                        });
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Kullanicilar_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Adres_1", "npAdres_1")
                        .WithOne("npKullanicilar_1")
                        .HasForeignKey("YemekSitesi_API_1.Models.Kullanicilar_1", "adresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("npAdres_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Menuler_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Menu_1", "npMenu_1")
                        .WithMany("npMenuler_1")
                        .HasForeignKey("menuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSitesi_API_1.Models.Urunler_1", "npUrunler_1")
                        .WithMany("npMenuler_1")
                        .HasForeignKey("urunID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("npMenu_1");

                    b.Navigation("npUrunler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Kategoriler_1", null)
                        .WithMany("npRestaurant_1")
                        .HasForeignKey("Kategoriler_1kategoriID");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_Menu_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Menu_1", "npMenu_1")
                        .WithMany("npRestaurant_Menu_1")
                        .HasForeignKey("menuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSitesi_API_1.Models.Restaurant_1", "npRestaurant_1")
                        .WithMany("npRestaurant_Menu_1")
                        .HasForeignKey("restaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("npMenu_1");

                    b.Navigation("npRestaurant_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_Urun_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Restaurant_1", "npRestaurant_1")
                        .WithMany("npRestaurant_Urun_1")
                        .HasForeignKey("restaurantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSitesi_API_1.Models.Urunler_1", "npUrunler_1")
                        .WithMany("npRestaurant_Urun_1")
                        .HasForeignKey("urunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("npRestaurant_1");

                    b.Navigation("npUrunler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Sepet_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Kullanicilar_1", "npKullanicilar_1")
                        .WithMany("npSepet_1")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("npKullanicilar_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Siparisler_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Menuler_1", "npMenuler_1")
                        .WithMany("npsiparisler_1")
                        .HasForeignKey("menulerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSitesi_API_1.Models.Restaurant_1", "npRestaurant_1")
                        .WithMany("npSiparisler_1")
                        .HasForeignKey("restaurantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSitesi_API_1.Models.Urunler_1", "npUrunler_1")
                        .WithMany("npsiparisler_1")
                        .HasForeignKey("urunID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSitesi_API_1.Models.Kullanicilar_1", "npKullanicilar_1")
                        .WithMany("npSiparisler_1")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("npKullanicilar_1");

                    b.Navigation("npMenuler_1");

                    b.Navigation("npRestaurant_1");

                    b.Navigation("npUrunler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Urunler_1", b =>
                {
                    b.HasOne("YemekSitesi_API_1.Models.Kategoriler_1", "npKategoriler_1")
                        .WithMany("npUrunler_1")
                        .HasForeignKey("kategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("npKategoriler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Adres_1", b =>
                {
                    b.Navigation("npKullanicilar_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Kategoriler_1", b =>
                {
                    b.Navigation("npRestaurant_1");

                    b.Navigation("npUrunler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Kullanicilar_1", b =>
                {
                    b.Navigation("npSepet_1");

                    b.Navigation("npSiparisler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Menu_1", b =>
                {
                    b.Navigation("npMenuler_1");

                    b.Navigation("npRestaurant_Menu_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Menuler_1", b =>
                {
                    b.Navigation("npsiparisler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Restaurant_1", b =>
                {
                    b.Navigation("npRestaurant_Menu_1");

                    b.Navigation("npRestaurant_Urun_1");

                    b.Navigation("npSiparisler_1");
                });

            modelBuilder.Entity("YemekSitesi_API_1.Models.Urunler_1", b =>
                {
                    b.Navigation("npMenuler_1");

                    b.Navigation("npRestaurant_Urun_1");

                    b.Navigation("npsiparisler_1");
                });
#pragma warning restore 612, 618
        }
    }
}
